name: Oyster
version: @version@
main: cc.sfclub.game.Oyster
api-version: 1.16
description: Universal minigame framework. commit @commitHash@ build by @buildBy@ at @buildDate@
website: https://bukkit.rip/oyster
